### ISSUE TITLE
Basic Instructions?

### ISSUE THREAD

**Issue by DavidCDean** [mozilla/rescuefox#27]
So dragging the mouse around seems to change perspective, but no other keys seem to initiate movement.  Is there an intro text somewhere?

**Comment by dmose** [comment]
There isn't.  There are no keyboard controls; use the mouse to click on
things you want to jump to.

Dan

**Comment by DavidCDean** [comment]
It turned out it was just being cranky earlier in the day... double clicks were working when I revisited later.
